#!/usr/bin/with-contenv bash
# shellcheck shell=bash

export RAILS_ENV=production
export PATH="${PATH}:/app/www/bin"
export RAILS_SERVE_STATIC_FILES=false

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 3000" \
        cd /app/www s6-setuidgid abc /usr/bin/bundle exec rails s -p 3000
